apiVersion: v1
kind: ReplicationController
metadata:
  name: plex
  namespace: default
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      imagePullPolicy: Always
      containers:
      - name: plex
        image: timhaak/plex
        ports:
        - containerPort: 32400
          name: web
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: "/config"
        - name: data
          mountPath: "/data"
      volumes:
      - name: config
        nfs:
          server: freenas.hell.corp 
          path: "/mnt/vol0/k8s/plex/config"
      - name: data
        nfs:
          server: freenas.hell.corp 
          path: "/mnt/vol0"
